global.pause = false;
global.getPos =false;
global.points = 0;

global.Questions = ["notin", "Who invented the telephone?", 
"What mythical creature is\nan onion related to?",
"What is Alice in Wonderland based off of?",
"What’s the name of our Professor?",
"What is the hardest mineral?",
"what year did the titanic sink?",
"who has the most rings in\nNBA history?",
"Who painted the mona lisa?",
"What planet is known as the blue planet?",
"What is the only planet not\nnamed after the roman greek god?",
"who designed air jordan 14?",
"Who was the second president?",
"Who directed the \nnightmare before christmas?",
"Who was the second climber\nto send cowboy direct?",
"Who wrote In the Hall of Mountain King?"];


global.answerOne = ["oops",
"Andrew Graham Bell",
"Donkeys",
"A School's Mascot",
"Professor Wescott",
"Bedrock",
"1934",
"Stephen Curry",
"Michelangelo",
"Neptune",
"Europea",
"Tinker Hatfield",
"James Madison",
"Jeffery Katzenburg",
"Will Smith",
"Hank Williams",
];

global.answerTwo = ["oops",
"Nicholas Tesla",
"Ogre",
"Dungeons and Dragons",
"Doctor Strange",
"Obsidian",
"1924",
"Bill Russell",
"Raphael",
"Earth",
"Pluto",
"Blinky Blead",
"Abraham Lincoln",
"Henry Selick",
"Chris Sharma",
"Aretha Franklin",
];

global.answerThree = ["oops",
"Andrew Graham Bell",
"The Onionizer",
"Tomathy Ann Borderland",
"Professor Cave Johnson",
"Diamond",
"2023",
"Michael Jordan",
"Da Vinci",
"America",
"Earth",
"Michael Jordan",
"John Adams",
"Tim Burton",
"Alex Honnold",
"Edvard Grieg",
];

global.answerFour = ["oops",
"Andrew Graham Bell",
"Goblins",
"a bad trip lol",
"Professor Lewis",
"Netherite",
"1912",
"Desmond Bane",
"Donatello",
"Uranus",
"Uranus",
"Phil Knight",
"Thomas Jefferson",
"Rick Heinrichs",
"Matt Segal",
"Taylor Swift",
];